### ISSUE TITLE
IE11 Support

### ISSUE THREAD

**Issue by guybedford** [calebdwilliams/construct-style-sheets#12]
We're recommending this polyfill for usage in the SystemJS 6.x (yet to be released) implementation of CSS modules (https://github.com/systemjs/systemjs/blob/6.x/docs/module-types.md#css-modules).

Because SystemJS supports IE11, we've had to note that this polyfill can't be used for CSS modules in IE11.

IE11 does fully support mutation observers though, so it may simply be that avoiding the spread operator, arrow functions, for-of and providing a simple Symbol fallback in the codebase that IE11 support could be completely possible.

Would you be open to a PR along these lines?

**Comment by calebdwilliams** [comment]
Yeah, I’m open to a PR on this. There is another PR open that is a pretty major refactor. I’ll work this week to get that completed and merged then ping you when it’s ready for your changes.

**Comment by edoardocavazza** [comment]
Also, classes are not supported and babel output may be throw because of https://github.com/babel/babel/issues/4452.

**Comment by guybedford** [comment]
I suppose https://github.com/calebdwilliams/construct-style-sheets/issues/20 is a necessary starting point first too.

**Comment by calebdwilliams** [comment]
#20 has a PR open at #21. To be honest, this is my first major project to maintain and I'm not sure about the proper etiquette of reviewing my own PRs :joy:. Mind taking a look at that one as part of this?

**Comment by calebdwilliams** [comment]
Running this through the Babel REPL seems to yield the right results. I don't have an IE11 machine hand at this moment though. @guybedford would you mind checking if this works in IE11 and reporting back? I am especially interested in the `Symbol.hasInstance`, but unfortunately have no way of checking any of this.
