### ISSUE TITLE
Add CI testing & coverage

### ISSUE THREAD

**Issue by Lodin** [calebdwilliams/construct-style-sheets#16]
To be sure the project has all tests passing in all target browsers and the coverage is OK, the CI service should be added. I personally use the [Travis CI](https://travis-ci.com) for testing and [Codecov](https://codecov.io) for coverage.

**Comment by calebdwilliams** [comment]
Yup, I already have this in my backlog. Thanks for creating this issue though.

**Comment by calebdwilliams** [comment]
Travis integration added in #18.

**Comment by calebdwilliams** [comment]
Code coverage and badging added in #22
