### ISSUE TITLE
Find alternative to isConnected

### ISSUE THREAD

**Issue by calebdwilliams** [calebdwilliams/construct-style-sheets#25]
**Describe the bug**
`Node.isConnected` is not supported by IE11.

**To Reproduce**
Run the package through Babel and then in IE11.

**Expected behavior**
The polyfill should work as expected

**Desktop (please complete the following information):**
 - IE11

**Comment by calebdwilliams** [comment]
It's possible `isConnected` is no longer necessary. Playing around with this.

**Comment by Lodin** [comment]
We can just require the [`isConnected` polyfill](https://github.com/zaclummys/is-connected-node) in documentation. It is quite small, only [323B](https://bundlephobia.com/result?p=is-connected-node@1.0.0-beta) according to Bundlephobia.

Unfortunately, we cannot drop `isConnected` if we want to support actions like `insertRule`. They require adopters to have a sheet.

**Comment by calebdwilliams** [comment]
Yeah, was playing with that last night. I want to not use a dependency if possible, but we might have to.

**Comment by Lodin** [comment]
Well, we still need `WeakMap`, `Map`, `Symbol`, `Promise`... Why not to require `isConnected` as well? This is not a feature that can be simply emulated, so I would prefer to rely on dependency here.

**Comment by calebdwilliams** [comment]
I put this in #28, but let's not include polyfills for `WeakMap`, `Map`, `Symbol` or `Promise` inside this package to ensure interop with polyfills in consuming projects.
