### ISSUE TITLE
[Suggestion] Remove support for CSSStyleSheet methods

### ISSUE THREAD

**Issue by Lodin** [calebdwilliams/construct-style-sheets#30]
While working on #28, I found that it is quite tricky to implement support for `CSSStyleSheet` methods like `insertRule`, `deleteRule`, etc. for `ShadyCSS`. The root of the problem is that `ShadyCSS` works with CSS text while the polyfill operates with `HTMLStyleElement`. So it is not easy to just apply `CSSStyleSheet` methods on the resulting style sheet the `ShadyCSS` produces.

So my suggestion is to drop the support for `CSSStyleSheet` methods. They are odd because do not change the visible CSS text, quite hard to implement, and speaking from my experience are very rare to use. Dropping them not only gives us the ability to be consistent between different browsers. It would also simplify the general code that has to be more complicated due to restrictions this support brings. 

E.g., we probably would be able to remove `createNodeIterator` part because we can work with disconnected styles. Also, it won't be necessary to add mutation observer to all shadow roots because we could run adoption logic on the disconnected elements. BTW, the issue with `Node.prototype.isConnected` will simply disappear.

One more argument for my suggestion is that the `ShadyCSS` does not support these methods as well. It just sticks the styles together in one big stylesheet and appends it to the `<head>`. And it is ok for more than 99% of all requirements.

**Comment by calebdwilliams** [comment]
The original version of this project didn’t support those methods, but I believe @Jack-Works added support because he needs that for his project, so I hesitate to remove support for a feature that’s in use especially just for compact with ShadyDOM. Regardless, this would need to be a breaking change.

**Comment by Jack-Works** [comment]
A widely used project JSS is using these methods.

So you are right, removing these methods supporting is a breaking change

**Comment by Lodin** [comment]
Ok, I got the situation. Let's emulate that behavior then 😎
