### ISSUE TITLE
Add typings for TypeScript

### ISSUE THREAD

**Issue by calebdwilliams** [calebdwilliams/construct-style-sheets#36]
**Describe the bug**
Add a `d.ts` file that will add the `replace` and `replaceSync` methods to the global `CSSStyleSheet` interface for TypeScript.

**Expected behavior**
A TypeScript project importing this polyfill should not throw on the following

```typescript
let sheet = new CSSStyleSheet();
sheet.replace(`* { box-sizing: border-box; }`);
```

**Additional context**

**Comment by Lodin** [comment]
Can I take it?

**Comment by calebdwilliams** [comment]
@Lodin Sure. If you have time. I've been swamped at work and home and haven't had much time to put that in. Happy to have that.

**Comment by TechQuery** [comment]
There is still no `.d.ts` in `dist/` of NPM package...
