### ISSUE TITLE
Exception while loading this polyfill together with webcomponents-lite polyfill

### ISSUE THREAD

**Issue by timaschew** [calebdwilliams/construct-style-sheets#39]
**Describe the bug**
An exception is thrown just by loading the polyfill.
This is the exception:
```
0: NotFoundError
lui-all.min.js (17875,366)

[object DOMException]: {code: 8, message: "NotFoundError", name: "NotFoundError"}
code: 8
message: "NotFoundError"
name: "NotFoundError"

__proto__: DOMExceptionPrototype

0: NotFoundError
lui-all.min.js (17875,366)
```

**Screenshot**
<img width="756" alt="Screen Shot 2019-11-13 at 11 34 23" src="https://user-images.githubusercontent.com/110870/68755960-a15e3700-0609-11ea-85fd-2e75226afbdb.png">

**To Reproduce**
Load this polyfill in addition: https://github.com/webcomponents/webcomponentsjs/blob/v1/webcomponents-lite.js

**Expected behavior**
No exception are thrown when loading the page with webcomponents-lite polyfill and construct-style-sheets polyfill.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Edge
 - Version 44

**Comment by timaschew** [comment]
Using latest version of the [polymer polyfill](https://unpkg.com/browse/@webcomponents/webcomponentsjs@2.4.0/webcomponents-bundle.js) is showing the same error multiple times but without any stack trace (line numbers)

**Comment by calebdwilliams** [comment]
Thanks for letting me know. I don't have immediate access to a Windows machine so I can't diagnose, but @Lodin might be able to help on this one.

**Comment by Lodin** [comment]
@timaschew, trying to reproduce the bug, I created the following [glitch example](https://glitch.com/edit/#!/striped-gouda) and tested it with the Edge 44.18362.387.0. Unfortunately, looks like I cannot reproduce the bug with this code. Could you take a look at it and provide a repro of the bug you found?

**Comment by timaschew** [comment]
@calebdwilliams me neither, I've used a VM from here: https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/

@Lodin 
The element needs to be used in the markup. Your example works fine in my Edge.
But please try this:

```html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
</head>
<body>
<script src="https://unpkg.com/@webcomponents/webcomponentsjs@2.4.0/webcomponents-bundle.js"></script>
<script src="https://unpkg.com/construct-style-sheets-polyfill@2.3.0/dist/adoptedStyleSheets.js"></script>
<template id="x-test-template">
	<h1>x-test component</h1>
</template>
<script>
class Test extends HTMLElement {
  constructor() {
    super()
      const template = document.getElementById('x-test-template')
      this.attachShadow({mode: 'open'}).appendChild(document.importNode(template.content, true))
  }
}
customElements.define('x-test', Test);
customElements.whenDefined('x-test').then(() => console.log('success'));
</script>
<x-test></x-test>
</body>
</html>
```

**Comment by calebdwilliams** [comment]
Hey @timaschew, could you check the latest version (2.3.1) and let us know if this can stay closed?

Thanks!

**Comment by timaschew** [comment]
Hi, great it's working. But I have a warning due to source map for 2.3.1
I'm using this CDN: https://cdn.jsdelivr.net/npm/construct-style-sheets-polyfill@2.3.1/dist/adoptedStyleSheets.min.js
