### ISSUE TITLE
Seems not to work on My Custom controls (on some it does)

### ISSUE THREAD

**Issue by jogibear9988** [calebdwilliams/construct-style-sheets#42]
**Describe the bug**
Look at https://node-projects.github.io/web-component-designer/build/
at the element "designer-tab-control"

Som of the instances have styles, some not...

**To Reproduce**
Go to https://node-projects.github.io/web-component-designer/build/ with firefox

**Expected behavior**
It should look the same in Chrome and in FF

**Comment by jogibear9988** [comment]
elements view in chrome:

![image](https://user-images.githubusercontent.com/364896/69493848-41db1380-0eb4-11ea-9ac6-034ed1f501a2.png)

**Comment by jogibear9988** [comment]
and in firefox

![image](https://user-images.githubusercontent.com/364896/69493854-4ef80280-0eb4-11ea-8308-4b6c546eb7ef.png)

**Comment by jogibear9988** [comment]
but in the main area the cunstructible style sheets work also in FF...

![image](https://user-images.githubusercontent.com/364896/69493861-620ad280-0eb4-11ea-8125-30a7c63ba77a.png)

**Comment by calebdwilliams** [comment]
Thanks for reporting this. I’m on vacation right now so I might not get to this immediately, but I will get to this ASAP.

**Comment by calebdwilliams** [comment]
Could you send me the source code here or via DM on Twitter ([@calebwilliams12](https://twitter.com/calebwilliams12)), I would be better able to diagnose this.

**Comment by jogibear9988** [comment]
the source are in the repo named above

**Comment by calebdwilliams** [comment]
Got it. So it looks like there is a race condition between your tab control's mutation observer and the one used by the polyfill to make sure the style sheets don't get removed. What command can I use to run the project?

**Comment by jogibear9988** [comment]
Source is here: https://github.com/node-projects/web-component-designer
Build via Typescript
Run Via polymer serve :
polymer serve --port 8000 --open

**Comment by calebdwilliams** [comment]
Perfect. I'll see if I can't figure this out over the next few days.

**Comment by jogibear9988** [comment]
@calebdwilliams you got any chance to look at this?

**Comment by jogibear9988** [comment]
@calebdwilliams 
I now included a breakpoint in my component when applying the style via "adopted Stylesheets" but then it works 

;-(

**Comment by jogibear9988** [comment]
If I remove the "isConnected" check  in "initAdoptedStyleSheets" it works

**Comment by calebdwilliams** [comment]
That actually helps a lot. Let me play with it again.

**Comment by jogibear9988** [comment]
thx

**Comment by jogibear9988** [comment]
And again a little bit more info.

I've 3 node-projects-designer-tab-control in my page.
on two the Adopted Stylesheet does not work.

One is in the sahdow root of node-projects-attribute-editor, there it does not get the "style" added to it's shadow root.

**Comment by jogibear9988** [comment]
@calebdwilliams 
maybe we could make the check optional? so I could disable it via parameter? (okay, I also would like it better to find the root cause)

**Comment by calebdwilliams** [comment]
Looks like this is an issue with running the adopted stylesheets in the element's constructor rather than the `connectedCallback` which was the advice from Google awhile back. Let me see what I can do.

**Comment by calebdwilliams** [comment]
@Lodin You made a comment in #25 that `isConnected` is still necessary, but running a few (admittedly basic tests). It seems like it's OK to remove now. Do you remember the specifics of that?

**Comment by jogibear9988** [comment]
if you look here https://wicg.github.io/construct-stylesheets/#proposed-solution
they assign the adopted in the constructor.
and parse the style in the connected (but I did that also in the constructor)

**Comment by calebdwilliams** [comment]
Yeah, the initial implementation in Chrome had a bug that would disallow using it in the constructor, but it was a bug. I just never went back and tried. I'm looking for another way to accomplish this.

**Comment by jogibear9988** [comment]
can't we add a mutationobserver when the connected is false, wich listens if the element was added to the dom?
or is there no mutation event for this, only for the children?

**Comment by calebdwilliams** [comment]
No, connecting to the DOM doesn't trigger a mutation event; you'd need to add a childList watcher to every `DocumentOrShadowRoot` instance to get that. Although you _might_ be able to proxy `IsConnected`, but that feels like overkill.

**Comment by jogibear9988** [comment]
sure that this can be proxied? maybe it's not set, maybe it's readonly

i think the observer on every shadowroot is not good for perf....

maybe don't need the connected check any more...

**Comment by calebdwilliams** [comment]
I mean, technically we already have an observer on every shadow root to make sure no one deletes one of the style elements. It's not particularly bad, but it might lead to a race condition if we do anything else.

**Comment by jogibear9988** [comment]
isnt the adopted array imutable? so we should know about changed styles when the setter is called again?

**Comment by Lodin** [comment]
> You made a comment in #25 that isConnected is still necessary, but running a few (admittedly basic tests). It seems like it's OK to remove now.

@calebdwilliams, unfortunately, we cannot remove it. If you delete checking for `isConnected` [here](https://github.com/calebdwilliams/construct-style-sheets/blob/master/src/init.js#L90), [this](https://github.com/calebdwilliams/construct-style-sheets/blob/master/test/polyfill.test.js#L356) test will fail.

> Do you remember the specifics of that?

It happens because of `insertRule` (or similar `CSSStyleSheet` functions) which require the style sheet of the element to be in place which is available only if element is connected to DOM. That's the same reason you create `iframe` instead of using the `style` element in memory. So this check is required and cannot be avoided.

**Comment by calebdwilliams** [comment]
@Lodin, that's what I thought it was, but for whatever reason I can't get tests to run on my work computer and don't really have time to wrestle with that particular question. I'll see if I can't find a work around.

**Comment by calebdwilliams** [comment]
So it appears wrapping that call in a `Promise.resolve` or `window.requestAnimationFrame` will make things work. Seems we have a race condition with `isConnected`.  Personally the latter makes sense since it is interfacing with the paint API anyway. Either way it's just queuing a microtask. I'll get this released later today.

**Comment by calebdwilliams** [comment]
Fixed! @jogibear9988 check version 2.3.5.

**Comment by calebdwilliams** [comment]
@jogibear9988 Can you confirm this fixes your issue?

**Comment by calebdwilliams** [comment]
Closing for the time being. Will reopen if there is need.
