### ISSUE TITLE
adopted style sheet is not overriding the styles declared in the custom element

### ISSUE THREAD

**Issue by akc42** [calebdwilliams/construct-style-sheets#43]
**Describe the bug**
The poly

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by calebdwilliams** [comment]
Looks like styles aren’t getting appended to the end of the location. I’ll take a look at this when I get a chance.

**Comment by akc42** [comment]
Sorry for the lack of information.  I started this issue off - them went off to read the spec to see what it said about the order of the styles.  Then I realised that lit-element also adds styles at the end of the list of styles if adoptedStylesheets isn't implemented and then realised that I didn't need to use them for what I was trying do do (change `:host {display: none}` to `:host {display: block}`  because I could just do `:host(:not([open])) {display: none} :host([open]) {display: block}` as a fixed style instead.

Net result was I thought I had not even opened an issue and because I wasn't sure if it was a bug or not - the spec is not exactly transparent - I decided to leave it.

Looks like it did open a bug - and that you think the spec says that adoptedStylesheets override the styles that are there.

**Comment by calebdwilliams** [comment]
Yeah, it does. This used to work before a large-scale refactor that was done recently. The `adoptedStyleSheets` take precedence. I've made a small change that will ensure proper cascade order in _most_ cases and will make that more robust in the future when I'm not on family duty.

At any rate this will work as expected in version 2.3.3.
