### ISSUE TITLE
Latest release on npm includes livereload script that breaks usage.

### ISSUE THREAD

**Issue by enjikaka** [calebdwilliams/construct-style-sheets#44]
https://unpkg.com/construct-style-sheets-polyfill

which resolves to version 2.3.3 as of now includes `(function(l, r) { if (l.getElementById('livereloadscript')) return; r = l.createElement('script'); r.async = 1; r.src = '//' + (window.location.host || 'localhost').split(':')[0] + ':35729/livereload.js?snipver=1'; r.id = 'livereloadscript'; l.head.appendChild(r) })(window.document);`
which breaks in my application when importing the polyfill.

https://unpkg.com/construct-style-sheets-polyfill@2.3.2 does not have this issue.

**Comment by Lodin** [comment]
Wait, that looks suspicious. The latest version of this package according to the commit history is 2.3.2. There should be no 2.3.3.

**Comment by calebdwilliams** [comment]
Honestly it looks like the dev version got checked in somehow. Regardless, I've published 2.3.4 and changed my npm credentials FWIW. Thanks for bringing this up @enjikaka.

**Comment by enjikaka** [comment]
Thanks for the fix! 

Trying this out on https://podd.app now. Seems to be running well! 🎉
