### ISSUE TITLE
How to use `construct-style-sheets` on iframe

### ISSUE THREAD

**Issue by hieunc229** [calebdwilliams/construct-style-sheets#53]
When using construct-style-sheets for iframe, the current document has `adoptedStyleSheets` but not the iframe.
I've tried to fork a local repository and create a `ConstructuredStyleSheet({ targetWindow })`. Which will initiate the `adoptedStyleSheet` to the target window and its document. But it is just so buggy.

Is there any way the iframe will inherit `adoptedStyleSheets` or somehow to use it on an iframe?

---

**To Reproduce**
1. Install `construct-style-sheets` as instruction
2. use `import construct-style-sheets-polyfill
3. Adopt stylesheets
```js
iframeDocument.adoptedStyleSheets = [styleFile];
```

**Expected behavior**
The iframe should allow adopting new stylesheets

**Actual behavior**
On the iframe, adoptedStyleSheets is `undefined`. Error received:
```
TypeError: undefined is not an object
```

**Additional context**
 - OS: OSX
 - Browser: Safari (13.1.2)
 - Enviroment: React, iframe was [react-frame-component](https://github.com/ryanseddon/react-frame-component)

**Comment by calebdwilliams** [comment]
Ideally you’ll load the script in every document you need `adoptedStyleSheets` Because the `document` and `window` instances are unique. 

While I can watch all shadow roots in a document, it’s unrealistic to watch for new frames all the way down.

**Comment by hieunc229** [comment]
Thanks for the answer @calebdwilliams. 

Your recommendation was what I've been doing, but I'm not so confident in my changes. The polyfill uses global variables, they are conflicting between the iframe and the main page global variables.

For example, the original code uses a global `document` instead of an assigned variable. There are a few variables that depend on these global variables (i.e `hasShadyCss `, `frame`).

Then I realized the `window` variable, which a few other things related to (i.e `OldCSSStyleSheet`, `CSStyleSheet`, the style value of the observer, etc.)

It is unrealistic to watch for new frames, but having an initial function would be reusable. 
I don't want to request the feature, just my thoughts.

Something like:
```js
initateConstructedStyleSheet({
    targetWindow: window, // or iframe.contentDocument
    targetDocument: document, // or iframe.contentDocument, or just take document from targetWindow
})
```

**Comment by calebdwilliams** [comment]
Yeah, I’d pursue this but sheets cant be reused across documents so it doesn’t quite make sense.

**Comment by hieunc229** [comment]
Sorry for didn’t make my point clear.

I mean the polyfill should be reusable, not the sheets. Since It uses global variables, it causes encapsulation problem.

If you do plan to working on it, I’d be so glad. Though, I’m aware you might not have time.

Thanks for the library anyway.
