### ISSUE TITLE
removeExcludedStyleSheets doesn't remove any stylesheets after it finds a non-excluded sheet

### ISSUE THREAD

**Issue by dyoder** [calebdwilliams/construct-style-sheets#54]
**Describe the bug**

Short version: [this line][1] should be `continue` not `return`.

[1]: https://github.com/calebdwilliams/construct-style-sheets/blob/b6b1988ec842ba60059436811a7ed4707771bd1d/src/adopt.js#L84

Slightly longer version: when checking for excluded stylesheets, `removeExcludedStyleSheets` returns after finding a stylesheet that should not be included. This prevents it from checking additional stylesheets.

**To Reproduce**

Given two stylesheets `s1` and `s2`:

```
document.adoptedStyleSheets = [ s1, s2 ]
document.adoptedStyleSheets = [ s1 ]
```

will fail to remove `s2` because it finds `s1` first.

**Expected behavior**

The stylesheet `s2` is removed.

**Comment by calebdwilliams** [comment]
Hey @dyoder, 2.4.0 includes your changes. Thanks for the contribution!
