### ISSUE TITLE
RFC: Integrity version

### ISSUE THREAD

**Issue by Lodin** [calebdwilliams/construct-style-sheets#57]
It's been a while but I'm here with new thoughts about the polyfill implementation.

### Integrity

The idea came from #45 and #46. Before, I thought that we should operate with real `CSSStyleSheet` classes to avoid any inconsistency that may come from using the wrapper class. However, after some investigation, I couldn't find any specific cases we aren't able to use the wrapper class for if we create it with the `new` operator. E.g., we cannot set it directly to the `style` element `sheet` property. All we can do is adding the class to `adoptedStyleSheet` array or call its methods. And any of this can be done in the scope of a single class. Please, correct me if I'm wrong.

This architecture promises to be more straight, and the package should become smaller.

### Development tools

What about including `typescript` and `eslint` for this project? I think we could use their power to make the maintenance of the project easier.

For `eslint` I have a couple of suggestions:
- I have my own [set of rules](https://github.com/Lodin/eslint-config-poetez). I created it following the idea: "Any rule should be included until it causes pain". Cons: it does not follow any specific style guide.
- We can use the [airbnb style guide](https://github.com/airbnb/javascript). I'm not a big fan of this particular style guide (it is kinda opinionated) but since we are targeting IE, it should be ok.

**UPD**: BTW, I'm open to any other variants. I just don't know another style guide that can compete with Airbnb. Google, probably, but AFAIK it is full of strange decisions and is way more opinionated than Airbnb.

**Comment by Lodin** [comment]
Well, I don't like using the compiler itself as well. I prefer `@babel/preset-typescript`.

> I’m out of pocket until next week. Let me think about it and we can circle up then.

Sure

**Comment by calebdwilliams** [comment]
The code to maintain referential integrity has been released. Closing this issue for now. I am open to adopting TypeScript, will look at that in January.
