### ISSUE TITLE
Stray console.log in published 2.4.0 pkg

### ISSUE THREAD

**Issue by pinkhominid** [calebdwilliams/construct-style-sheets#58]
**Describe the bug**
The recent 2.4.0 package logs unnecessary messages to the dev console. The line is not found in the repo source, just the published pkg.

**To Reproduce**
Install, import, use latest package in Firefox or Safari.

**Expected behavior**
Shouldn't log messages to the console.

**Screenshots**
<img width="589" alt="image" src="https://user-images.githubusercontent.com/206228/92197567-1ec89180-ee40-11ea-9d1d-ffca37ce611e.png">

**Desktop (please complete the following information):**
 - OS: all
 - Browser: FF, Safari

**Comment by calebdwilliams** [comment]
Hey @pinkhominid, sorry about that. I've removed those from the dist. Thanks for pointing that out!
