### ISSUE TITLE
[question] Does the iframe work better than a template element?

### ISSUE THREAD

**Issue by Lodin** [calebdwilliams/construct-style-sheets#6]
I continue exploring the abilities of `CSSStyleSheet` object and this polyfill and found that the polyfill implementation uses the `iframe` element. Just wonder why not `template` element or even `DocumentFragment`? Is it connected with how browser parses and uses the CSS?

**Comment by calebdwilliams** [comment]
The style element needs to be connected in order to create the style sheet object. This seemed to be the lightest-weight way to get that object and avoid side effects.

**Comment by Lodin** [comment]
Oh I see, thanks!
