### ISSUE TITLE
TypeError: Right hand side of instanceof is not an object

### ISSUE THREAD

**Issue by DumbledoreD** [calebdwilliams/construct-style-sheets#60]
**Describe the bug**
`TypeError: Right hand side of instanceof is not an object` is raised from `instanceOfStyleSheet` when the polyfill is used with LitElement. 

**To Reproduce**
```
git clone https://github.com/PolymerLabs/lit-element-starter-js.git
cd lit-element-starter-js
yarn install
yarn add construct-style-sheets-polyfill
```

Add the following to `./dev/index.html` head
```
<script src="../node_modules/construct-style-sheets-polyfill/dist/adoptedStyleSheets.js"></script>
```

Start server `yarn serve` and visit http://localhost:8000/dev/index.html

Observe the error in the console, and `my-element` is not rendered.

**Expected behavior**
No error and working LitElement

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Safari
 - Version: 12.1, 13.1

**Comment by calebdwilliams** [comment]
Hey @DumbledoreD, I ran through your instructions and everything is working as expected using Safari 12.2.1 and Firefox 79.0 and Firefox 80.0.1. In all versions I tested, I was also able to confirm `my-element.shadowRoot.adoptedStyleSheets` was being used instead of `LitElement`'s solution.

**Comment by DumbledoreD** [comment]
Can confirm the error is gone. Tested the setup on BrowserStack. I'll close this. Thanks!
