### ISSUE TITLE
Overriding HTMLElement.attachShadow breaks other polyfills

### ISSUE THREAD

**Issue by gluck** [calebdwilliams/construct-style-sheets#62]
**Describe the bug**
`attachShadow` is defined (per spec) on `Element` but this polyfill sets it on `HTMLElement.prototype`
If anyone else later changes `Element.prototype.attachShadow`, their code is never called (on HTMLElements), because this library's polyfill takes precedence, and revert to the native attachShadow code (captured during init).

**To Reproduce**
https://codesandbox.io/s/attachshadow-bug-demo-w33wp
Loading it on Chrome shows "Should be called" on console (this library doesn't patch attachShadow).
Loading it on Firefox doesn't.
Switching the order of polyfills fixes the issue for Firefox (need to reload the sandbox for the prototypes to be reset)

**Expected behavior**
attachShadow being defined on Element as per the spec, that's where it should be defined to play fine with other polyfills/hooks.

**Additional context**
Polyfill confirmed to break if applied after this one:
[@lwc/synthetic-shadow](https://github.com/salesforce/lwc/blob/master/packages/%40lwc/synthetic-shadow/src/faux-shadow/element.ts#L121)

**Comment by calebdwilliams** [comment]
Oh dang, great catch. I'll get a fix out for that immediately.

**Comment by calebdwilliams** [comment]
This is fixed in version 2.4.2. Thanks for bringing this to my attention.

**Comment by gluck** [comment]
That was fast ! Thanks !

**Comment by gluck** [comment]
Note that it's working fine with LWC polyfill now, except for an exception:

```
Uncaught TypeError: node.shadowRoot.adoptedStyleSheets is undefined
    iter adoptedStyleSheets.js:228
    adoptAndRestoreStylesOnMutationCallback adoptedStyleSheets.js:232
```

That's because LWC is modifying the shadowRoot property and returns something which is not of type `ShadowRoot`, hence don't get the augmented properties set by this polyfill.
You might want to safeguard against the exception with an additional check, assuming we don't want this polyfill to apply in this case.

**Comment by calebdwilliams** [comment]
Hey, I’m not sure I follow. Are you saying that lwc patches `attachShadow` and doesn’t rerun a `ShadowRoot`?

**Comment by gluck** [comment]
Exactly, but it does so only for lwc components, for other elements it reverts to native attachShadow, so this polyfill would still work for those.
