### ISSUE TITLE
[Feature Request] Usage with text editors

### ISSUE THREAD

**Issue by sdyalor** [calebdwilliams/construct-style-sheets#64]
Is there a way to expose an import like 
`import { adoptedStyleSheets } from 'construct-style-sheets-polyfill';`

Reason: Usage for vscode completion and warning free.
![image](https://user-images.githubusercontent.com/50224521/99082493-39cb2680-2592-11eb-8972-31f307d5039f.png)

**Comment by calebdwilliams** [comment]
Toppings _should_ be exported. I’ll take a look tomorrow.

**Comment by sdyalor** [comment]
There are workarounds but duno how to do the right way with typescript :'(

**Comment by calebdwilliams** [comment]
Looks like the `d.ts` file wasn't included in the files array in package.json. That has been fixed in 2.4.6, but probably can be improved. I'll look at a wholesale adopting of TypeScript in January, but `replace` and `replaceSync` should be added to Intellisense now.
