### ISSUE TITLE
Styles are not applied for elements created when document is loading

### ISSUE THREAD

**Issue by Artur-** [calebdwilliams/construct-style-sheets#67]
**Describe the bug**
An adoptedStyleSheets set during page load is not applied when `initPolyfill` is called when the document has finished loading.

**To Reproduce**
```
<!DOCTYPE html>
<html>
  <head>
    <script src="https://unpkg.com/construct-style-sheets-polyfill@2.4.6/dist/adoptedStyleSheets.js"></script>
  </head>
  <body>
    <script type="text/javascript">
      // This code needs to run after the polyfill has loaded but before initPolyfill has been run
      debugger;
      const div = document.createElement("div");
      const shadowRoot = div.attachShadow({ mode: "open" });
      const spanWithText = document.createElement("span");
      spanWithText.innerText = "I should be blue";
      shadowRoot.appendChild(spanWithText);
      const sheet = new CSSStyleSheet();
      sheet.replaceSync(" * { color: blue }");
      shadowRoot.adoptedStyleSheets = [sheet];
      document.body.appendChild(div);
    </script>

    <button
      onclick="javascript:s = document.querySelector('div').shadowRoot; s.adoptedStyleSheets = s.adoptedStyleSheets;"
    >
      Fix me
    </button>
  </body>
</html>
```
or the live version at https://artur.app.fi/stylesheet-polyfill-bug.html

**Expected behavior**
The text in the example case is blue when the style sheet is applied. When opening the page in Chrome, the text is blue (native implementation). When opening the page in Firefox or Safari, the text is black. Re-applying `adoptedStyleSheets` causes the text to turn blue also in Firefox and Safari.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] macOS
 - Browser [e.g. chrome, safari] Chrome (works), Safari Firefox (broken)

**Comment by Artur-** [comment]
https://github.com/Artur-/construct-style-sheets/commit/d4c27f17b45d924a1415acf4c5b4e783a0787540 seems to fix this but it is quite unclear to me if this is the correct way to fix it.

**Comment by calebdwilliams** [comment]
Hey, your code looks fine to me. I’m not sure the best way to test that either tbh, but let’s create a PR and work on it together.

**Comment by Artur-** [comment]
Created #70 with a description of how I tried to make a test
