### ISSUE TITLE
[Regression] Incorrect style embed priority.

### ISSUE THREAD

**Issue by BrychanOdlum** [calebdwilliams/construct-style-sheets#69]
**Describe the bug**
When a web component defines its own styles within the `innerHTML`, this polyfill prepends the styles above, giving the `innerHTML` stylesheet priority. This is opposite to the native behaviour of Chrome. When testing in Chrome 88 the styles defined by `adoptedStyleSheets` take priority.

**To Reproduce**
1. Go to the following JSFiddle: https://jsfiddle.net/j06uL2np/
2. Test in Chrome 88, it shows "IT WORKS!".
3. Test in Chrome 63, it does not. (Can perhaps test within another build prior to constuctable stylesheets support).

**Expected behavior**
adoptedStyleSheets should take priority in this case. View the demo, it should read "IT WORKS!".

**Screenshots**

**Desktop:**
 - OS: macOS
 - Browser Chrome 88, Chrome 63

**Comment by BrychanOdlum** [comment]
This looks like a regression as it was working in v2.3.3.

**Comment by calebdwilliams** [comment]
Yup, something’s wrong. Confirmed in Firefox. I’ll take a look when I get a chance.

**Comment by calebdwilliams** [comment]
This is fixed 2.4.11.
