### ISSUE TITLE
With the polyfill loaded, Firefox 91.0 no longer shows any styles in style inspector

### ISSUE THREAD

**Issue by franktopel** [calebdwilliams/construct-style-sheets#83]
**Describe the bug**
With the polyfill loaded, it is no longer possible to inspect any element's styles in the Firefox developer tools Inspector tab. No styles are presented at all. This not only applies to elements using constructed stylesheet, but also to all other regular HTML elements. 

Current Firefox developer edition (92.0b2) also doesn't support constructed stylesheets, but does not have this issue.

**To Reproduce**
Load any page including JS with the polyfill in Firefox <= 91 on MacOS. Inspect any element in the page.

**Expected behavior**
Styles show up in inspector, at least for those elements not making use of constructed stylesheets.

**Screenshots**
Firefox 91.0:
<img width="867" alt="grafik" src="https://user-images.githubusercontent.com/10668603/129179949-7c1b6233-a03a-4004-bd8b-bf43e96db9ef.png">
<img width="997" alt="grafik" src="https://user-images.githubusercontent.com/10668603/129179864-af104ec3-5137-48e8-a04a-d7dac3ba2fa9.png">

Firefox Developer Edition 92.0b2 (still not supporting constructed stylesheets natively):
<img width="996" alt="grafik" src="https://user-images.githubusercontent.com/10668603/129181397-a56c71f9-bdfb-4f5c-b76c-2d29061b181c.png">

**Desktop (please complete the following information):**
 - OS: MacOS 12.0 (Monterey) Beta (21A5294g) // Windows 10 (1909 Enterprise N)
 - Browser: Firefox
 - Version: 91.0

**Additional context**
I've just had my windows colleague check, the same issue also exists on Firefox 91 / Windows 10.

**Comment by Lodin** [comment]
Hi @franktopel, thanks for filing the issue.

Which version of the polyfill do you use? `v2.x.x` or `v3.0.0`?

**Comment by franktopel** [comment]
```
    
"construct-style-sheets-polyfill": "^3.0.0-0"
```

**Comment by franktopel** [comment]
It has to be noted that this is especially troublesome since Firefox 91 is going to be the next ESR version.

**Comment by Lodin** [comment]
Hi @franktopel. I tried to reproduce your case but failed. Here is my [attempt](https://qfivc.csb.app/). I can see CSS styles for both imported css file and for constructed style sheets. 

**Regular CSS**
![image](https://user-images.githubusercontent.com/8037479/129485659-4f4873d1-0ea0-49e3-a34e-c1a4af4fa818.png)
**Constructed StyleSheet CSS**
![image](https://user-images.githubusercontent.com/8037479/129485667-a43274c5-68a2-4912-9f69-1932fbc748f1.png)

I'm using Windows. How this project works for you?

You may noticed that FF doesn't display Shadow DOM for the `<x-test>`. However, that's the old bug of Firefox that I face quite often.

**Comment by franktopel** [comment]
Will check your example. We're using a Vite.js/rollup-based build stack, btw.

**Comment by franktopel** [comment]
I tried to create a small reproducer, but failed. I think thi can be closed for the time being, until I can provide a reproducer at least.
