### ISSUE TITLE
`new CSSStyleSheet().media` is not object

### ISSUE THREAD

**Issue by mantou132** [calebdwilliams/construct-style-sheets#91]
**Describe the bug**
unimplemented https://developer.mozilla.org/en-US/docs/Web/API/MediaList

**To Reproduce**
Safari visit https://codepen.io/mantou132/pen/mdMXXrN

**Expected behavior**
No error

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Safari
 - Version 15

**Comment by Lodin** [comment]
Hey @mantou132, thanks for your post and sorry for the late answer. I'm going to take care of it.
