### ISSUE TITLE
npm version >7

### ISSUE THREAD

**Issue by jogibear9988** [calebdwilliams/construct-style-sheets#92]
Is there any reason why you need npm version to be >7 ?

**Comment by calebdwilliams** [comment]
cc @Lodin, looks like you added that. Any info you can give @jogibear9988?

**Comment by Lodin** [comment]
Hey guys, sorry for late answer.

Hmm, I don't remember the exact reason but it looks like I thought that it should affect only the package developers. For devs, it is necessary to preserve the correct version of the `package-lock.json`.

I guess we could safely remove this restriction if it affects not only devs.
